apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: devops-assesement
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: myapp:latest # Replace with your Docker image
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        ports:
        - containerPort: 8080
